name: Build Armbian with Landscape 

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    name: Compile Armbian Image with Landscape
    env:
      BOARD: arm64
      RELEASE: trixie
      BRANCH: current
      BUILD_DESKTOP: no
      BUILD_MINIMAL: yes
      KERNEL_CONFIGURE: yes
      KERNEL_GIT: shallow
      NETWORKING_STACK: none

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl zip unzip p7zip-full python3 python3-pip qemu-user-static binfmt-support

    - name: Clone Armbian build framework
      run: |
        git clone --depth=1 https://github.com/armbian/build.git armbian
        cd armbian
        mkdir -p userpatches/overlay
        mkdir -p userpatches

    - name: Add Landscape init config
      run: |
        cp ./landscape_init.toml armbian/userpatches/overlay/landscape_init.toml

    - name: Add customize-image.sh
      run: |
        cp ./customize-image.sh armbian/userpatches/customize-image.sh
        chmod +x armbian/userpatches/customize-image.sh

    - name: Compile Armbian image
      working-directory: armbian
      run: |
        ./compile.sh \
          build \
          BOARD=${{ env.BOARD }} \
          BRANCH=${{ env.BRANCH }} \
          BUILD_DESKTOP=${{ env.BUILD_DESKTOP }} \
          BUILD_MINIMAL=${{ env.BUILD_MINIMAL }} \
          KERNEL_CONFIGURE=${{ env.KERNEL_CONFIGURE }} \
          RELEASE=${{ env.RELEASE }} \
          KERNEL_GIT=${{ env.KERNEL_GIT }} \
          NETWORKING_STACK=${{ env.NETWORKING_STACK }}

    - name: Locate output image
      id: locate_image
      run: |
        IMAGE_PATH=$(find output/images -type f -name "*.img" | head -n 1)
        echo "IMAGE_PATH=$IMAGE_PATH" >> $GITHUB_ENV

    - name: Upload image to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.IMAGE_PATH }}
        tag_name: "auto-${{ github.run_id }}"
        name: "Armbian Landscape Image (arm64)"
        body: |
          自动构建的 Armbian 镜像，集成 Landscape 初始化配置与首次启动自动设置。
          - 架构: arm64
          - 板卡: ${{ env.BOARD }}
          - 发行版: ${{ env.RELEASE }}
          - 内核分支: ${{ env.BRANCH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
