name: Build and Release Landscape Router (arm64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-landscape-router:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Build Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential bc u-boot-tools curl zip unzip git

    - name: Clone Armbian Build Tools
      run: git clone https://github.com/ThisSeanZhang/landscape-build $HOME/landscape-build

    - name: Configure Environment
      run: |
        export BOARD=arm64
        export BRANCH=current
        export BUILD_DESKTOP=no
        export BUILD_MINIMAL=yes
        export KERNEL_CONFIGURE=yes
        export RELEASE=bookworm
        export KERNEL_GIT=shallow
        export NETWORKING_STACK="none"

    - name: Copy Configuration Files
      run: |
        cp userpatches/overlay/landscape_init.toml $HOME/landscape-build/userpatches/overlay/
        cp userpatches/customize-image.sh $HOME/landscape-build/userpatches/

    - name: Execute Compile Script
      run: |
        cd $HOME/landscape-build
        bash ./compile.sh \
          BOARD=$BOARD \
          BRANCH=$BRANCH \
          BUILD_DESKTOP=$BUILD_DESKTOP \
          BUILD_MINIMAL=$BUILD_MINIMAL \
          KERNEL_CONFIGURE=$KERNEL_CONFIGURE \
          RELEASE=$RELEASE \
          KERNEL_GIT=$KERNEL_GIT \
          NETWORKING_STACK=$NETWORKING_STACK

    - name: Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: landscape-router-build
        path: $HOME/landscape-build/output/

    - name: Release Artifacts to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: $HOME/landscape-build/output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
